name: Run make_install

on:
  workflow_dispatch:

jobs:
  make-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./make_scripts/make_install.sh

      - name: Run make_install.sh
        run: ./make_scripts/make_install.sh
